version: '3.8'

services:
  webtoon:
    image: trybekszybek/go_webtoons_web_api
    container_name: go-webtoon-dl
    ports:
      - "8080:80"
    restart: "no"
    # If you want compose to build the image from the repo, replace image with:
    # build: .
    environment:
      - API_KEY_HASH=
